config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    post 'fooditems/create' => 'orders#create_fooditem'
    get 'fooditems/new' => 'orders#new_fooditem'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :restaurants

  devise_for :admins

  resources :restaurants do
    get 'orders' => 'restaurants/orders#index'
    resources :foods, controller: 'restaurants/foods'
  end

  namespace :admin do
    resources :locations
    resources :restaurants
    resources :orders do
      get 'by_restaurants' => 'orders#by_restaurants', on: :collection
      get 'by_locations' => 'orders#by_locations', on: :collection
    end
  end

  root 'orders#new'

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :orders
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < AdminController

  before_action :set_location, except:[:new, :create, :index]

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    if @location.save
      flash[:success] = 'New Location Added!'
      redirect_to admin_locations_path
    else
      flash[:danger] = 'Failed!'
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      flash[:success] = 'Location Updated!'
      redirect_to admin_locations_path
    else
      flash[:danger] = 'Failed!'
      render :edit
    end      
  end

  def index
    @locations = Location.all
  end

  def show
  end

  def destroy
    if @location.destroy
      flash[:success] = 'Location Deleted!'
    else
      flash[:danger] = 'Failed!'
    end
    redirect_to admin_locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name)    
  end

  def set_location
    @location = Location.find(params[:id])
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= simple_form_for(@location, url: admin_location_path, method: :patch) do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Update', class:'btn btn-primary' %>
<% end %>

app/views/admin/locations/edit.html.erb
<h2>Edit Location</h2>
<%= render 'admin/locations/form' %>

app/views/admin/locations/index.html.erb
<div class="col-md-12">

  <h2 class="text-center">所有地點</h2>

  <% if @locations.exists? %>
  
    <table class="table">
      <thead>
        <tr>
          <th> Id </th>
          <th> Name </th>
          <th colspan="2"></th>
        </tr>
      </thead>
      
      <tbody>
        <% @locations.each do |location| %>
          <tr>
            <td> <%= location.id %> </td> 
            <td> <%= location.name %> </td> 
            <td> <%= link_to('Edit', edit_admin_location_path(location), class: "btn btn-info") %></td>
            <td> <%= link_to('Delete', admin_location_path(location), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    <p>There is no location yet. <%= link_to 'Create now ?', new_admin_location_path %></p>
  <% end %>
</div>

app/views/admin/locations/new.html.erb
<h2>Create New Location</h2>
<%= simple_form_for(@location, url: admin_locations_path) do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Create', class:'btn btn-primary' %>
<% end %>