config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    post 'fooditems/create' => 'orders#create_fooditem'
    get 'fooditems/new' => 'orders#new_fooditem'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :restaurants

  devise_for :admins

  resources :restaurants do
    get 'orders' => 'restaurants/orders#index'
    resources :foods, controller: 'restaurants/foods'
  end

  namespace :admin do
    resources :locations
    resources :restaurants
    resources :orders do
      get 'by_restaurants' => 'orders#by_restaurants', on: :collection
      get 'by_locations' => 'orders#by_locations', on: :collection
    end
  end

  root 'orders#new'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :foods, dependent: :destroy
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < AdminController
  before_filter :find_restaurant

  def index
    @restaurants = Restaurant.all
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:success] = 'Restaurant Updated!'
      redirect_to admin_restaurants_path
    else
      flash[:danger] = 'Failed!'
      render :edit
    end
  end

  private

  def find_restaurant
    @restaurant = Admin::Restaurant.find(params[:id]) if params[:id]
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/restaurant/foods_controller.rb
class Restaurant::FoodsController < RestaurantsController
  def new
    if current_restaurant
      @food = current_restaurant.foods.new
    else
      redirect_to new_restaurant_session_path
    end
  end

  def create
    @food = current_restaurant.foods.create(food_params)
    if @food.save
      flash[:success] = 'New Food Added!'
      redirect_to restaurant_foods_path
    else
      flash[:danger] = 'Failed!'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def index
    @foods = current_restaurant.foods
  end

  def show
  end

  def destroy
  end

  private
  def food_params
    params.require(:food).permit(:name)
  end
  def set_food
    @food = Food.find(params[:id])
  end
end

app/controllers/restaurants/foods_controller.rb
class Restaurants::FoodsController < RestaurantsController

  before_action :set_food, except: [:new, :create, :index]

  def new
    if current_restaurant
      @food = current_restaurant.foods.new
    else
      redirect_to new_restaurant_session_path
    end
  end

  def create
    @food = current_restaurant.foods.create(food_params)
    if @food.save
      flash[:success] = 'New Food Added!'
      redirect_to restaurant_foods_path
    else
      flash[:danger] = 'Failed!'
      render :new
    end
  end

  def edit
  end

  def update
    if @food.update(food_params)
      flash[:success] = 'Food Updated!'
      redirect_to restaurant_foods_path
    else
      flash[:danger] = 'Failed!'
      render :edit
    end
  end

  def index
    @foods = current_restaurant.foods
  end

  def show
  end

  def destroy
    if @food.destroy
      flash[:success] = 'Food Deleted!'
      redirect_to restaurant_foods_path
    else
      flash[:danger] = 'Failed!'
      render :index
    end    
  end

  private
  def food_params
    params.require(:food).permit(:name)
  end
  def set_food
    @food = current_restaurant.foods.find(params[:id])
  end
end

app/controllers/restaurants/orders_controller.rb
class Restaurants::OrdersController < RestaurantsController
  def index
    @orders = current_restaurant.orders.includes(:fooditems)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  layout "restaurant/application"
  before_action :authenticate_restaurant!
end

app/helpers/restaurant/foods_helper.rb
module Restaurant::FoodsHelper
end

app/helpers/restaurant/orders_helper.rb
module Restaurant::OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/common/restaurant/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center"><%= link_to "Back to Front", root_url %></p>
  
  <p class="text-center">
    Copyright ©2015 Come2eat <br>
    Design by <a href="">GoodNine</a>
  </p>
</footer>

app/views/common/restaurant/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <%= link_to 'Come2eat', restaurant_foods_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class= "<%= 'active' if controller_name == 'orders' %>">
          <%= link_to '所有訂單', restaurant_orders_path %>
        </li>
        <li class= "<%= 'active' if controller_name == 'foods' %>">
          <%= link_to '所有品項', restaurant_foods_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_restaurant.blank? %>
          <li><%= link_to("Sign Up", new_restaurant_registration_path) %></li>
          <li><%= link_to("Log In", new_restaurant_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_restaurant.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to("帳號設定", edit_restaurant_registration_path )%></li>
              <li> <%= link_to("登出", destroy_restaurant_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>