config/routes.rb
Rails.application.routes.draw do

  resources :orders do
    post 'fooditems/create' => 'orders#create_fooditem'
    get 'fooditems/new' => 'orders#new_fooditem'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :restaurants

  devise_for :admins

  resources :restaurants do
    get 'orders' => 'restaurants/orders#index'
    resources :foods, controller: 'restaurants/foods'
  end

  namespace :admin do
    resources :locations
    resources :restaurants
    resources :orders do
      get 'by_restaurants' => 'orders#by_restaurants', on: :collection
      get 'by_locations' => 'orders#by_locations', on: :collection
    end
  end

  root 'orders#new'

end

app/models/order.rb
class Order < ActiveRecord::Base

  scope :recent, -> { order('updated_at DESC') }

  belongs_to :user
  belongs_to :location

  has_many :fooditems, dependent: :destroy

  accepts_nested_attributes_for :fooditems,
    :allow_destroy => true,
    reject_if: :reject_fooditems

  validate :fooditems_available?
  validates_presence_of :name

  def reject_fooditems(attributes)
    attributes['restaurant_id'].blank? || attributes['quantity'].blank? || attributes['food_id'].blank?
  end

  def fooditems_available?
    if fooditems.empty?
      errors[:base] << 'No fooditems present'
      false
    else
      true
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

  before_action :set_order, except:[:new, :create, :index, :by_restaurants, :by_locations]

  def index
    @orders = Order.order(:user_id).recent
  end

  def update
    if @order.update(order_params)
      flash[:success] = 'Order Updated!'
      redirect_to admin_orders_path
    else
      flash[:danger] = 'Failed!'
      render :edit
    end  
  end

  def show
    @fooditems = Fooditem.where(order_id: @order)
  end

  def destroy
  end

  def by_restaurants
    @restaurants = Restaurant.all
  end

  def by_locations
    @locations = Location.all
  end

  private
  def order_params
    params.require(:order).permit(:location_id, :restaurant_id, :food_id, :description)
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!, except:[:new]
  before_action :set_order, except:[:new, :create, :index]
  before_action :get_restaurants, only:[:new, :create, :edit]
  #before_action :previous_page

  def new
    if user_signed_in?
      @order = current_user.orders.new
    else
      @order = Order.new
    end
  end

  def create
    @order = current_user.orders.new(order_params)
    if @order.save
      flash[:notice] = 'New Order Added!'
      redirect_to order_path(@order)
    else
      flash[:alert] = @order.errors.full_messages
      @fooditem = @order.fooditems.new
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update(order_params)
      flash[:notice] = 'Order Updated!'
      redirect_to order_path(@order)
    else
      flash[:alert] = 'Failed!'
      render :edit
    end
  end

  def index
    @orders = current_user.orders.order('updated_at DESC')
  end

  def show
    @fooditems = @order.fooditems
  end

  def destroy
    if @order.destroy
      flash[:notice] = 'Order Deleted!'
    else
      flash[:alert] = 'Failed!'
    end
    redirect_to orders_path
  end

  def create_fooditem
    @fooditem = @order.fooditems.create(fooditem_params)
    @fooditem.save
  end

  private
  def order_params
    params.require(:order).permit(:name, :user_id, :location_id, :description, fooditems_attributes: [:id, :food_id, :restaurant_id, :quantity, :_destroy])
  end

  def fooditem_params
    #params.require(:fooditem).permit(:id, :food_id, :restaurant_id, :quantity, :_destroy)
    params.permit(:id, :order_id, :food_id, :restaurant_id, :quantity, :_destroy)
  end

  def set_order
    @order = current_user.orders.find(params[:id])
  end

  def get_restaurants
    @restaurants = Restaurant.all
  end

end

app/controllers/restaurants/orders_controller.rb
class Restaurants::OrdersController < RestaurantsController
  def index
    @orders = current_restaurant.orders.includes(:fooditems)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
=begin
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
=end
end

app/helpers/restaurant/orders_helper.rb
module Restaurant::OrdersHelper
end

app/views/admin/orders/by_locations.html.erb
<div class="col-md-12">

  <h2 class="text-center"> All Orders </h2>
  <%= render 'admin/orders/partial/links' %>
  <% if @locations.exists? %>
    <% @locations.each do |l| %>
      <h3> <%= l.name %> </h3>
      <table class="table">
        <thead>
          <tr>
            <th>品項</th>
            <th>數量</th>
          </tr>
        </thead>
        <tbody>
          <% l.orders.each do |order| %>
            <% if order.fooditems.exists? %>
              <tr>
                <% order.fooditems.each do |item| %>
                  <td><%= item.food.name %></td>
                  <td>
                    <%= "#{item.quantity}+" %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          <% end %>        
        </tbody>
      </table>
    <% end %>

  <% else %>
    <%= render 'admin/orders/partial/no_order' %>
  <% end %>
</div>

app/views/admin/orders/by_restaurants.html.erb
<div class="col-md-12">

  <h2 class="text-center"> All Orders </h2>
  <%= render 'admin/orders/partial/links' %>
  <% if @restaurants.exists? %>
    <% @restaurants.each do |r| %>
      <h3> <%= r.name %> </h3>
      <table class="table">
        <thead>
          <tr>
            <th>品項</th>
            <th>數量</th>
          </tr>
        </thead>
        <tbody>
          <% r.foods.each do |food| %>
            <% if food.fooditems.exists? %>
              <tr>
                <td><%= food.name %></td>
                <td>
                  <% food.fooditems.each do |item| %>
                    <%= "#{item.quantity}+" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>        
        </tbody>
      </table>
    <% end %>

  <% else %>
    <%= render 'admin/orders/partial/no_order' %>
  <% end %>

</div>

app/views/admin/orders/create.html.erb
<h1>Admin::Orders#create</h1>
<p>Find me in app/views/admin/orders/create.html.erb</p>

app/views/admin/orders/destroy.html.erb
<h1>Admin::Orders#destroy</h1>
<p>Find me in app/views/admin/orders/destroy.html.erb</p>

app/views/admin/orders/edit.html.erb
<h2>Edit Order <%= @order.id %></h2>

<%= simple_form_for(@order, url: admin_order_path, method: :patch) do |f| %>
  <%= @order.user.email %>
  <%= f.input :location_id, as: :select, collection: Location.all, value: :id,:include_blank => false %>
  <%= f.input :description, html: { rows: 7 }, disabled: true %>
  <%= f.submit 'Update', class:'btn btn-primary' %>
<% end %>

app/views/admin/orders/index.html.erb
<div class="col-md-12">

  <h2 class="text-center"> All Orders </h2>
  <%= render 'admin/orders/partial/links' %>
  <% if @orders.exists? %>
  
    <table class="table">
      <thead>
        <tr>
          <th> 單號 </th>
          <th> Name </th>
          <th> Location </th>
          <th> User </th>
          <th> Description </th>
          <th> Last Update </th>
          <th colspan="2"></th>
        </tr>
      </thead>
      
      <tbody>
        <% @orders.each do |order| %>
          <tr id= <%= "#{order.user.email}_order_#{ order.id }" %> >
            <td> <%= link_to order.id, admin_order_path(order) %> </td>
            <td> <%= order.name %> </td>
            <td> <%= order.location.name %> </td>
            <td> <%= order.user.email %> </td>
            <td> <%= order.description %> </td>
            <td> <%= order.updated_at.to_formatted_s(:short) %> </td> 
            <td> <%= link_to('Edit', edit_admin_order_path(order), class: "btn btn-info") %></td>
            <td> <%= link_to('Delete', admin_order_path(order), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", remote: true) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    <%= render 'admin/orders/partial/no_order' %>
  <% end %>
</div>

app/views/admin/orders/new.html.erb
<h1>Admin::Orders#new</h1>
<p>Find me in app/views/admin/orders/new.html.erb</p>

app/views/admin/orders/show.html.erb
<%= render 'partial/show_by_restaurant' %>

app/views/admin/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>